### PR TITLE
(fix) Exclude public/mockServiceWorker.js from git as recommended

### PR DESCRIPTION
**Pull request by tom-mi**
* see https://github.com/mswjs/msw/discussions/1015

### CODE REVIEW

**Comment by rkipsch** [comment]
Hey, in some projects we do have other stuff in the public folder that need to copied.

**Comment by tom-mi** [comment]
Yes, I thought about this as well. I did not find an elegant solution, the only other idea I have would be something like this:
```
export default defineConfig(({ mode }) => {
    return {
        // ...
        ...(mode === 'development' && { publicDir: 'public-dev' }),
    };
});
```
This has the downside that stuff you need on both dev & prod needs to be duplicated. Any other ideas?

**Comment by defaude** [comment]
Thanks @rkipsch for reminding about projects that actually **do** use the `public` folder 😅

What about not messing around in Vite too much => `mockServiceWorker.js` ends up in the output folder. And then we just remove the file in the pipeline before uploading to S3?

**Comment by defaude** [comment]
Even nicer using a `postbuild` step to delete the file from the output dir 👍

**Pull request merged**
